# Conclusion
```{r, echo = FALSE, message = FALSE}
source(here::here("scripts/Clean/setup.R"))
```

## Take home message

In conclusion, our data analytics research project reveals a gradual global progress in achieving the Sustainable Development Goals (SDGs), with notable variations across continents. While Europe emerges as a leader in SDG accomplishment, Africa lags behind, while Asia, the Americas and Oceania demonstrate diverse performance trends. 

After carefully choosing our models, we have been able to show the influence of factors on goals. The coefficient of the dependent variables will depend on the objective of the concerned SDGs. The principal trend showed that most of the goals are influenced positively by our chosen variables. Nevertheless, concerning climate oriented SDGs (12 & 13), we have been able to show that the influence of most of their variables in their models will influence their score negatively. Nevertheless, due to the limited selected factors, climate related factors could have helped us to explain better understand how these two goals have the two best average score among all SDGs. 

The interconnections of SDGs is evident, with high achievement in one goal often correlating with success in others. The analysis indicates that the impact of climate disasters on SDG achievement is notably weak, with limited associations found between climate-related variables and specific goals. Although variables related to COVID-19 and conflicts show significance in SDG achievement, they explain limited variance for each objective.

As one might expect, SDG adoption fosters increased partnerships over the goals (goal 17), while Goal 9, focusing on industry, innovation, and infrastructure, exhibits a faster rate of advancement compared to other goals, being before or after 2015. Overall, our findings underscore the complex dynamics influencing global progress on SDGs and emphasize the need for continued efforts and strategic partnerships to address the interconnected challenges and disparities across different regions and goals.

## Limitations

We had to delete several countries due to a high percentage of missing values, which means that some interesting countries are not analyzed for every research question. For example we removed Afghanistan and Somalia from the data used to analyze the different factors impacting the SDG scores. 

In addition, we chose some variables as events and factors for our analysis based on our knowledge and ideas on what would have the most interesting impacts, but there are an infinity of possibilities. It is thus difficult to know if we focused on the most important variables to explain the different SDG scores across the world. 

Finally, following the regression analyses on our SDG score, we have been able to gain a comprehensive understanding of how different factors impact our SDG. However, due to the low explanatory power of some of the regression models probably cause by non significant relationship between the chosen independent variables and some goals omitted variable bias or over-fitting, we must exercise caution when drawing any conclusions from these results.

## Future work

Our research serves as an overview of the different characteristics of a country, their evolution thought time, as well as uncontrollable events that can affect the 17 SDG scores. In this regard, future work could investigate other factors' effects such as the type of country governance (dictatorship, democracy, etc.) or the tourism rate. Additionally, we could implement in our work more global factors (social/climate related) and focus on other kinds of events, including financial crises and elections. 

We kept our analysis on the goal level, however, each goal has several targets and indicators that help keep track of the achievement and set subgoals. It would be interesting to dive in each goal separately to study more specifically these different targets and indicators in order to get a more precise view of what aspect of each goal is impacted by the different factors. 

# References

Allen, C., Metternicht, G. and Wiedmann, T. (2018) ‘Initial progress in implementing the sustainable development goals (sdgs): A review of evidence from countries’, Sustainability Science, 13(5), pp. 1453–1467. doi:10.1007/s11625-018-0572-3. 

Çağlar, M. and Gürler, C. (2021) ‘Sustainable development goals: A cluster analysis of worldwide countries’, Environment, Development and Sustainability, 24(6), pp. 8593–8624. doi:10.1007/s10668-021-01801-6.

Grover, P. et al. (2021) ‘Influence of political leaders on Sustainable Development Goals – insights from Twitter’, Journal of Enterprise Information Management, 34(6), pp. 1893–1916. doi:10.1108/jeim-07-2020-0304.

Pereira, P. et al. (2022) ‘The Russian‐Ukrainian Armed Conflict Will Push Back the Sustainable Development Goals’, Geography and Sustainability, 3(3), pp. 277–287. doi:10.1016/j.geosus.2022.09.003.

Pradhan, P. et al. (2017) ‘A systematic study of Sustainable Development Goal (SDG) interactions’, Earth’s Future, 5(11), pp. 1169–1179. doi:10.1002/2017ef000632.

Rassanjani, S. (2018) ‘Ending poverty: Factors that might influence the achievement of Sustainable Development Goals (sdgs) in Indonesia’, Journal of Public Administration and Governance, 8(3), p. 114. doi:10.5296/jpag.v8i3.13504.

Shulla, K. et al. (2021) ‘Effects of covid-19 on the Sustainable Development Goals (sdgs)’, Discover Sustainability, 2(1). doi:10.1007/s43621-021-00026-x.

Sompolska-Rzechuła, A. and Kurdyś-Kujawska, A. (2021) ‘Towards understanding interactions between sustainable development goals: The role of climate-well-being linkages. experiences of EU countries’, Energies, 14(7), p. 2025. doi:10.3390/en14072025.
