# Data

```{r, echo = FALSE, message = FALSE}
source(here::here("scripts/Clean/setup.R"))
```

## Sources

We are collecting our Data from the sustainability development report (SDG), the international labour organization (ILOSTAT), the World Bank, Our world in data, the CATO institute, one from Kaggle (disasters: we couldn't find relevant accessible information from somewhere else) and GitHub. We found different datasets containing useful information in relation with the SDGs. The details about these data and the links are presented in the next question.

+-------------------------------------------+--------------------------------------------+
| Name of the Table                         | Source                                     |
+===========================================+============================================+
| D1_1_SDG                                  | https://dashboards.sdgindex.org/\          |
|                                           | downloads                                  |
+-------------------------------------------+--------------------------------------------+
| D2_2_Unemployment_rate                    | https://www.ilo.org/\                      |
|                                           | shinyapps/bulkexplorer3/\                  |
|                                           | ?lang=en&segment=indicator\                |
|                                           | &id=UNE_2EAP_SEX_AGE_RT_A                  |
+-------------------------------------------+--------------------------------------------+
| D3_0_GDP_per_capita                       | https://data.worldbank.org/\               |
|                                           | indicator/NY.GDP.PCAP.CD                   |
+-------------------------------------------+--------------------------------------------+
| D3_1_Military_expenditure_percent_GDP     | https://data.worldbank.org/\               |
|                                           | indicator/MS.MIL.XPND.GD.ZS                |
+-------------------------------------------+--------------------------------------------+
| D3_2_Military_expenditure_percent_gov_exp | https://data.worldbank.org/\               |
|                                           | indicator/MS.MIL.XPND.ZS                   |
+-------------------------------------------+--------------------------------------------+
| D4_0_Internet_usage                       | https://ourworldindata.org/\               |
|                                           | grapher/share-of-individuals-\             |
|                                           | using-the-internet                         |
+-------------------------------------------+--------------------------------------------+
| D5_0_Human_freedom_index                  | https://www.cato.org/\                     |
|                                           | human-freedom-index/2022                   |
+-------------------------------------------+--------------------------------------------+
| D6_0_Disaters                             | https://www.kaggle.com/\                   |
|                                           | datasets/brsdincer/all-natural-\           |
|                                           | disasters-19002021-eosdis                  |
+-------------------------------------------+--------------------------------------------+
| D7_0_COVID                                | https://github.com/\                       |
|                                           | owid/covid-19-data/tree/master/public/data |
+-------------------------------------------+--------------------------------------------+
| D8_0_Conflicts                            | https://datacatalog.worldbank.org/\        |
|                                           | search/dataset/0041070/\                   |
|                                           | Global-Spread-of-Conflict-by-\             |
|                                           | Country-and-Population                     |
+-------------------------------------------+--------------------------------------------+

## Description

During the wrangling process: we add data to our table (D1_1_SDG) based on different other datasets and match them based on the country, the country code, and the year. The table below shows all our 9 databases that we merge to have our final table for the analysis, as well as each variable of interest that we keep.

+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
| **Table\                | **Variable\          | **Explanation**                                                                                                                                                                                                                                                                                   | **\# obs before cleaning**          | **\# obs\                                                                 |
| Name**                  | Name**               |                                                                                                                                                                                                                                                                                                   |                                     | after cleaning**                                                          |
+=========================+======================+===================================================================================================================================================================================================================================================================================================+=====================================+===========================================================================+
| In all database         | code                 | Country code (ISO)                                                                                                                                                                                                                                                                                |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | country              | Name of the country                                                                                                                                                                                                                                                                               |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | year                 | Year of the observation (2000-2022)                                                                                                                                                                                                                                                               |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
| D1_1\_\                 | overallscore         | Overall score on all 17 SDGs (the score are % of achievement of the goals determined by the UN based on several indicators)                                                                                                                                                                       | 4140 observations of 120 variables  | 3818 observations of 21 variables                                         |
| SDG                     |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | goal1:goal17         | Score on each SDG except SDG 14 (16 variables)                                                                                                                                                                                                                                                    |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | population           | Number of people living in the country                                                                                                                                                                                                                                                            |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
| D2_2\_\                 | unemployment.rate    | Unemployment rate (% of the population 15 years old and older)                                                                                                                                                                                                                                    | 82800 observations of 8 variables   | 571 observations of 5 variables                                           |
| Unemployment_rate       |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
| D3_0\_\                 | GDPpercapita         | GDP per capita                                                                                                                                                                                                                                                                                    | 266 observations of 68 variables    | 3818 observations of 4 variables                                          |
| GDP_per_capita          |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
| D3_1\_\                 | MilitaryExpenditure\ | Military expenditures in percentage of GDP                                                                                                                                                                                                                                                        | 266 observations of 68 variables    | 3818 observations of 4 variables                                          |
| Military_expenditure\_\ | PercentGDP           |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
| percent_GDP             |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
| D3_2\_\                 | MilitaryExpenditure\ | Military expenditures in percentage of government expenditures                                                                                                                                                                                                                                    | 266 observations of 68 variables    | 3818 observations of 4 variables                                          |
| Military_expenditure\_\ | PercentGovExp        |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
| percent_gov_exp         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
| D4_0\_\                 | internet.usage       | Internet usage (% of the population)                                                                                                                                                                                                                                                              | 6570 observations of 4 variables    | 3433 observations of 4 variables                                          |
| Internet_usage          |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
| D5_0\_\                 | region               | Part of the world, group of countries (e.g. Eastern Europe, Dub-Saharan Africa, South Asia, etc.)                                                                                                                                                                                                 | 3465 observations of 141 variables  | 3339 observations of 18 variables                                         |
| Human_freedom_index     |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | hf_score             | Human Freedom score = mean of personal freedom (PF) and economic freedom (EF).                                                                                                                                                                                                                    |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | pf_law               | Rule of law, mean score of:                                                                                                                                                                                                                                                                       |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | -   Procedural justice                                                                                                                                                                                                                                                                            |                                     |                                                                           |
|                         |                      | -   Civil justice                                                                                                                                                                                                                                                                                 |                                     |                                                                           |
|                         |                      | -   Criminal justice                                                                                                                                                                                                                                                                              |                                     |                                                                           |
|                         |                      | -   Rule of law (V-Dem)                                                                                                                                                                                                                                                                           |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | pf_security          | Security and safety, mean score of:                                                                                                                                                                                                                                                               |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | -   Homicide                                                                                                                                                                                                                                                                                      |                                     |                                                                           |
|                         |                      | -   Disappearances conflicts,                                                                                                                                                                                                                                                                     |                                     |                                                                           |
|                         |                      | -   terrorism                                                                                                                                                                                                                                                                                     |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | pf_movement          | Freedom of movement (V-Dem)                                                                                                                                                                                                                                                                       |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Freedom of movement (CLD)                                                                                                                                                                                                                                                                         |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | pf_religion          | Freedom of religion                                                                                                                                                                                                                                                                               |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Religious organizatio repression                                                                                                                                                                                                                                                                  |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | pf_assembly          | Civil society entry and exit                                                                                                                                                                                                                                                                      |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Freedom of assembly                                                                                                                                                                                                                                                                               |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Freedom to form/run political parties                                                                                                                                                                                                                                                             |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Civil society repression                                                                                                                                                                                                                                                                          |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | pf_expression        | Direct attacks on the press                                                                                                                                                                                                                                                                       |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Media and expression (V-Dem)                                                                                                                                                                                                                                                                      |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Media and expression (Freedom House)                                                                                                                                                                                                                                                              |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Media and expression (BTI)                                                                                                                                                                                                                                                                        |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Media and expression (CLD)                                                                                                                                                                                                                                                                        |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | pf_identity          | Same-sex relationships                                                                                                                                                                                                                                                                            |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Divorce                                                                                                                                                                                                                                                                                           |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Inheritance rights                                                                                                                                                                                                                                                                                |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Female genital mutilation                                                                                                                                                                                                                                                                         |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | pf_score             | Mean of every PF component score                                                                                                                                                                                                                                                                  |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | ef_government        | Government consumption                                                                                                                                                                                                                                                                            |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Transfers and subsidies                                                                                                                                                                                                                                                                           |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Government investment                                                                                                                                                                                                                                                                             |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Top marginal tax rate                                                                                                                                                                                                                                                                             |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | State ownership of assets                                                                                                                                                                                                                                                                         |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | ef_legal             | Judicial independence                                                                                                                                                                                                                                                                             |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Impartial courts                                                                                                                                                                                                                                                                                  |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Protection of property rights                                                                                                                                                                                                                                                                     |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Military interference Integrity of the legal system Legal enforcementof contracts                                                                                                                                                                                                                 |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Regulatory costs                                                                                                                                                                                                                                                                                  |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Reliability of police                                                                                                                                                                                                                                                                             |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | ef_money             | Money growth                                                                                                                                                                                                                                                                                      |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Standard deviation of inflation                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Inflation: Most recent year                                                                                                                                                                                                                                                                       |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Freedom to own foreign currency                                                                                                                                                                                                                                                                   |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | ef_trade             | Tariffs                                                                                                                                                                                                                                                                                           |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Regulatory trade barriers                                                                                                                                                                                                                                                                         |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Black-market exchange rates                                                                                                                                                                                                                                                                       |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Movement of capital and people                                                                                                                                                                                                                                                                    |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | ef_regulation        | Credit market regulations                                                                                                                                                                                                                                                                         |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Labor market regulations                                                                                                                                                                                                                                                                          |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      | Business regulations                                                                                                                                                                                                                                                                              |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | ef_score             | Mean of every EF component score                                                                                                                                                                                                                                                                  |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
| D6_0\_\                 | continent            | Continents touched by the disasters such as floods, ouragan                                                                                                                                                                                                                                       | 14644 observations of 47 variables  | 2435 observations                                                         |
| Disaters                |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
|                         |                      |                                                                                                                                                                                                                                                                                                   |                                     | of 10 variables                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | total_deaths         | Number of total deaths caused by the disasters                                                                                                                                                                                                                                                    |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | no_injured           | Number of injured people                                                                                                                                                                                                                                                                          |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | no_affected          | Number of affected people                                                                                                                                                                                                                                                                         |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | no_homeless          | Number of people that lost their home and are now homeless                                                                                                                                                                                                                                        |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | total_affected       | Sum of people affected (sum of the variables: no_injured, no-affected, no_homeless)                                                                                                                                                                                                               |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | total_damages        | Total of infrastructure damages                                                                                                                                                                                                                                                                   |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
| D7_0\_\                 | deaths_per_million   | Number of people dead due to COVID                                                                                                                                                                                                                                                                | 349966 observations of 67 variables | 501 observations (only between 2020-2022, before no COVID) of 6 variables |
| COVID                   |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | cases_per_million    | Number of COVID cases                                                                                                                                                                                                                                                                             |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | stringency           | Government Response Stringency Index: composite measure based on 9 response indicators including school closures, workplace closures, and trave                                                                                                                                                   |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
| D8_0\_\                 | ongoing              | Variable coded 1 for more than 25 deaths in intrastate conflict and 0 otherwise according to UCDP/PRIO Armed Conflict Dataset 17.1.                                                                                                                                                               | 5016 observations of 18 variables   | 2782 observations of 8 variables                                          |
| Conflicts               |                      |                                                                                                                                                                                                                                                                                                   |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | sum_deaths           | Best estimate of deaths in all categories of violence (non-state, one-sided and state-based) recorded by the Uppsala Conflict Data Program in the country based on the UCDP GED dataset (unpublished 2016 data). The location of these events is used for estimating the extent of violence.      |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | pop_affected         | Share of population affected by violence in percentage (0 to 100) measured as described above based on population data from CIESIN, the PRIO-GRID structure as well as UCDP GED.                                                                                                                  |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | area_affected        | Area affected by conflict                                                                                                                                                                                                                                                                         |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+
|                         | maxintensity         | Two different intensity levels are coded: minor armed conflicts (1) and wars (2), Takes the max intensity of conflict in the country so that it is coded 2 if there is at least one war (\>=1000 deaths in intrastate conflict) during the year. Data from UCDP/PRIO Armed Conflict Dataset 17.1. |                                     |                                                                           |
+-------------------------+----------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------+

## Wrangling/cleaning

**Final structure of our merged database:** each country of the 166 countries from D1_1_SDG are observed each year from 2000 to 2022, thus each row has a key composed of (code, year) that uniquely identifies an observation. The other columns are the variables listed above. Due to some countries having a lot of missing information we will have to eliminate some of them, but we will still have more than 2000 rows in our database.

## Spotting mistakes and missing data (could be part of EDA too)

## Listing anomalies and outliers (could be part of EDA too)
