# Introduction

## Overview and Motivation

The adoption of the SDGs by the United Nation in 2015 marked a significant global commitment to address pressing issues such as poverty, inequalities, climate change, and more. The fact that these goals were unanimously adopted by 193 member states underscores their importance. This prompted us to ask ourselves, can we evaluate the progress? What has really been done so far? Although the SDGs have attracted considerable attention and backing, it is essential to evaluate the events preceding and following their implementation. Understanding the actions taken and progress made is essential in determining if these global commitments are resulting in tangible enhancements to individuals’ lives. By examining the evolution of all countries and their respective contributions towards achieving the SDGs, we can develop a comprehensive understanding of collective efforts and identify potential disparities or gaps. In our work, we will use various datasets, thus various factors that will be useful for understanding the different connections and influences of our selected variables over the SDG scores. As the economical, political and social situation is not the same in each country, we will be able to notice the difference of the influence of our factors over the countries' SDG scores. In addition, we will analyse the evolution over time of all the SDGs since its implementation in 2015. We hope that you will find our work as interesting as we did.

## Related Work

Given the scale and the challenge that revolves around the SDGs, there are many researches that have been done on the topic. We found some of them interesting to look at to get a better understanding of the topic. One of them, is none other than the report of the United Nations on the SDGs. This report is a comprehensive annual assessment of global and regional progress towards the SDGs. It is based on the latest available data and is prepared by the Statistics Division of the United Nations Department of Economic and Social Affairs.

* <a href="https://unstats.un.org/sdgs/report/2023/">The Sustainable Development Goals Report 2023</a>

Some papers focus on the factors influencing a specific goal and/or a country, such as Rassanjani (2018) that explores goal 1 (No Poverty) in Indonesia. Other papers study one specific factor, like Grover et al. (2021), that focus on the influence of political leaders. In addition, Çağlar and Gürler (2021) analysed 110 countries to create clusters based on the SDG scores, socioeconomic and politico-cultural indicators, that were found to be positively correlated with most of the SDG scores. Furthermore, Sompolska-Rzechuła and Kurdyś-Kujawska (2021) investigated how SDGs interact through human-environment linkage, while Pradhan et al. (2017) have found synergies between most of the SDGs, except SDG 12 (responsible consumption and production) with which tradeoffs are associated. However, Allen et al. (2018) discuss the initial progress on the implementation of SDGs and point out the fact that even if some progress are made, they are not homogeneous across countries and that there is still a lot to do in terms of evaluating the synergies between SDGs, as well as trade-offs. 

Our study aims to investigate the evolution of Sustainable Development Goal (SDG) scores over the years, including the annual progress of countries and the interconnections between SDGs. Additionally, we seek to examine the economic, social, and political indicators using the Human Freedom Index and various other variables, while also exploring the development of all SDGs across 166 countries.

The impact of different events on SDGs have been studied. For example, Shulla et al. (2021) look at the impact of COVID on the SDGs that are easily linked to it through a qualitative research. They also found that "not obvious" SDGs were affected, such as SDG 10 (Reducing Inequalities) and SDG 5 (Gender Equality). Another example is the research from Pereira et al. (2022) that found that the Russian-Ukrainian conflicts has negatively impacted the SDGs. Other papers focus on specific parts of the world to assess the impact of conflicts on SDG scores. We want to have a look at as many countries as possible to see if patterns emerge regarding this topic. We see that the impact of events on specific areas and/or SDGs have already been investigated. However, a more general overview of the effect of such events over all SDGs worldwide have not been conducted. Therefore, we will investigate this aspect in our paper.

## Research questions

1.  **Focus on factors**: What can explain the state of the countries regarding their sustainable development?

We will analyse different factors: scores from the Human Freedom Index, GDP per capita, military expenditures in percentage of GDP, unemployment rate, internet usage. You will find more precise informations about our chosen factors in data description section.

2.  **Focus on relationship between SDGs**: How are the different SDGs linked?

We aim to determine whether certain Sustainable Development Goals (SDGs) are interconnected, such that a high score in one SDG might imply a high score in another, and if we can make groups of SDGs that are comparable in that way.

3.  **Focus on time**: How has the adoption of the SDGs in 2015 influenced the achievement of SDGs?

We want to compare the score achievement of the different countries before and after 2015 to see if the adoption of SDG gave a real "push" to sustainable development. Indeed, there were scores calculated before the adoption of the 17 objectives.

4.  **Focus on events**: Is the evolution in sustainable development influenced by uncontrollable events, such as economic crisis, health crises and natural disasters?

We will analyse the impact of the COVID, natural disasters and conflicts (# deaths, damages, etc.) on the SDG scores. You will find more precise informations about how the impact of these events are materialized into our data description section.
